name: Generated APK AAB

env:
  main_project_module: app
  playstore_name: MAIS BURGUER

on:
  push:
    branches:
      - develop
      - 'release/**'
  workflow_dispatch:

jobs:
  build_test_security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ env.date_today }}-${{ env.repository_name }}-APK
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
          retention-days: 1
          compression-level: 6

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ env.date_today }}-${{ env.repository_name }}-AAB
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
          retention-days: 1
          compression-level: 6

      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest --stacktrace

      - name: Perform Security Checks
        run: |
          echo "Placeholder for security checks."
          echo "Consider adding tools like SAST (Static Application Security Testing) or dependency vulnerability scanning here."
          echo "Example: 'semgrep --config auto --metrics on .'"
          echo "Example: 'snyk test --gradle-project ${{ env.main_project_module }}'