name: Generated APK AAB

env:
  main_project_module: app
  playstore_name: MAIS BURGUER

on:
  push:
    branches:
      - develop
      - 'release/**'
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Debug APK for Real Device Testing
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Debug-${{ env.date_today }}-${{ env.playstore_name }}-APK
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
          retention-days: 1
          compression-level: 6

      - name: Build Debug AAB for Real Device Testing
        run: ./gradlew bundleDebug

      - name: Upload Debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: Debug-${{ env.date_today }}-${{ env.playstore_name }}-AAB
          path: ${{ env.main_project_module }}/build/outputs/bundle/debug/
          retention-days: 1
          compression-level: 6

      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest --stacktrace